# Generated by Django 2.2 on 2020-10-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('upvote', models.IntegerField(default=0)),
                ('donwvote', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
