# Generated by Django 2.2 on 2020-10-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('upvote', models.IntegerField(default=0)),
                ('donwvote', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AllQuestion',
        ),
    ]
