# Generated by Django 2.2 on 2020-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201011_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllQuestions',
            new_name='AllQuestion',
        ),
    ]
