# Generated by Django 2.2 on 2020-10-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201011_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allquestion',
            old_name='donwvote',
            new_name='downvote',
        ),
    ]
