# Generated by Django 2.2 on 2020-10-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201014_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvote',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='name',
            new_name='username',
        ),
    ]
