# Generated by Django 2.2 on 2020-10-14 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201014_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allquestion',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='question_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='question_upvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allquestion',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
