# Generated by Django 2.2 on 2020-10-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0014_auto_20201016_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='comment_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='comment_upvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Comments')),
                ('replied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Comment_reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
