# Generated by Django 2.2 on 2020-10-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20201019_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='allquestion',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
