# Generated by Django 2.2 on 2020-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_allquestion_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='content',
            field=models.TextField(default='default is added'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(default='Defualt is added'),
        ),
    ]
